version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: smashboard
      POSTGRES_PASSWORD: smashboard
      POSTGRES_DB: smashboard
    ports:
      - "5432:5432"
